#!/usr/bin/env python3
"Parse an old configuration file to a new one in json format"
import sys
from qmpy._parse_legacy import _parse_config_legacy


def main():
    """Main function of the script"""
    if len(sys.argv) < 2:
        print("Please specify a configuration file to parse.")
        exit()

    try:
        _parse_config_legacy(sys.argv[2])
    except OSError as e:
        print(e)


if __name__ == "__main__"
    main()
